# Jekyll configuration settings
title: MarcusFelling.com
description: A blog about things I learn at the keyboard - DevOps, CI/CD, Cloud, Automation, to name a few...
baseurl: "/"
url: "https://marcusfelling.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: true
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
