############################
# --- Required options --- #
############################

title: "Home"
description: "A blog about things I learn at the keyboard: DevOps, CI/CD, Cloud, Automation, to name a few..."
baseurl: "/"
url: "https://marcusfelling.com"
remote_theme: marcusfelling/blog-theme
author: Marcus Felling

navbar-links:
  Archive: "archives"


#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: marcusfelling
  linkedin: marcusfelling
# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: A blog about things I learn at the keyboard - DevOps, CI/CD, Cloud, Automation, to name a few….

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MarcusFelling.com"

# Add the website title to the title of every page
title-on-all-pages: false

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

readtime: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
view_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
navbar-var-length: false

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

######################################
# --- Colors / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs/
  - node_modules
  - playwright-report

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
